apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: mbtilserver
  name: mbtilserver
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  selector:
    matchLabels:
      app: mbtilserver
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mbtilserver
    spec:
      containers:
        - env:
            - name: PORT
              value: "5000"
            - name: SUB_DOMAIN
              value: "/api/tileserver"
            - name: DIRECTORY
              value: "/app/data/mbtiles/"
            - name: VERBOSE
              value: "1"
            - name: ALLOWED_HOSTS
              value: "*"
          image: correnticscontainers.azurecr.io/correntics/rust-mbtileserver:0.0.2
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          name: mbtilserver
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: datadir
              mountPath: /app/data
      volumes:
        - name: datadir
          azureFile:
            secretName: azure-secret
            shareName: kubernetes-data
            readOnly: false
      imagePullSecrets:
        - name: acr-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30


---
apiVersion: v1
kind: Service
metadata:
  name: mbtileserver
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: mbtilserver